#!/bin/bash

# Script de Teste do Sistema de Win Streaks
# Este script simula operações para testar o sistema

echo "🔥 === TESTE DO SISTEMA DE WIN STREAKS ==="
echo ""
echo "📋 O que este teste faz:"
echo "  1. Simula uma sequência de vitórias"
echo "  2. Testa o modo conservador"
echo "  3. Simula quebra de streak"
echo "  4. Testa progressão de níveis"
echo ""
echo "⚠️  Este é um teste visual - abra o console do navegador para ver os logs"
echo ""

# Verificar se o servidor está rodando
if ! lsof -i:8080 > /dev/null 2>&1; then
    echo "❌ Servidor não está rodando na porta 8080"
    echo "   Execute: npm run dev"
    exit 1
fi

echo "✅ Servidor encontrado na porta 8080"
echo ""
echo "🌐 Abra o navegador em: http://localhost:8080"
echo ""
echo "📊 Para visualizar o sistema:"
echo "  1. Abra a aplicação no navegador"
echo "  2. Procure pelo card 'Sistema de Win Streaks'"
echo "  3. Gere sinais clicando em 'Gerar Sinal'"
echo "  4. Marque os sinais como WIN para aumentar a streak"
echo "  5. Observe o progresso em tempo real"
echo ""
echo "🎯 OBJETIVOS DO TESTE:"
echo "  - Atingir 15 vitórias consecutivas (Meta inicial)"
echo "  - Ver modo conservador ativar em 70%+ do target"
echo "  - Observar progressão ao atingir meta"
echo "  - Novo target será 20 vitórias após primeira meta"
echo ""
echo "📝 LOGS IMPORTANTES NO CONSOLE:"
echo "  🔥 STREAK ATUAL: X/15 (Y%)"
echo "  ✅ PADRÃO FORTE DETECTADO"
echo "  🎯 TARGET ATINGIDO!"
echo "  📈 PROGRESSÃO! Nível X"
echo "  ❌ STREAK QUEBRADA"
echo ""

read -p "Pressione ENTER para abrir o navegador..."

# Tentar abrir o navegador
if command -v xdg-open > /dev/null; then
    xdg-open "http://localhost:8080"
elif command -v open > /dev/null; then
    open "http://localhost:8080"
else
    echo "Por favor, abra manualmente: http://localhost:8080"
fi

echo ""
echo "🎮 COMO TESTAR:"
echo ""
echo "1️⃣  AUMENTAR STREAK:"
echo "   - Clique em 'Gerar Sinal'"
echo "   - Marque como WIN (✓)"
echo "   - Repita várias vezes"
echo "   - Observe a barra de progresso aumentar"
echo ""
echo "2️⃣  MODO CONSERVADOR (após 10+ vitórias):"
echo "   - Sistema ficará mais seletivo"
echo "   - Probabilidade mínima aumenta"
echo "   - Apenas padrões testados são permitidos"
echo "   - Alerta visual aparecerá no card"
echo ""
echo "3️⃣  ATINGIR META (15 vitórias):"
echo "   - Card celebra com animação"
echo "   - Conquista é desbloqueada"
echo "   - Nível aumenta"
echo "   - Novo target: 20 vitórias"
echo ""
echo "4️⃣  QUEBRAR STREAK:"
echo "   - Marque um sinal como LOSS (✗)"
echo "   - Veja análise da causa no console"
echo "   - Sistema aprende com o erro"
echo "   - Streak reinicia do zero"
echo ""
echo "💡 DICA: Abra o Console do Navegador (F12) para ver todos os logs!"
echo ""
echo "🔍 VERIFICAÇÕES AUTOMÁTICAS:"
echo "  - Sistema rastreia cada WIN/LOSS"
echo "  - Calcula probabilidade ideal automaticamente"
echo "  - Ajusta thresholds baseado em performance"
echo "  - Reforça padrões de sucesso"
echo "  - Penaliza padrões de falha"
echo ""
echo "📊 ESTATÍSTICAS DISPONÍVEIS:"
echo "  - Streak Atual"
echo "  - Recorde Pessoal"
echo "  - Target Atual"
echo "  - Nível de Progressão"
echo "  - Histórico de Streaks"
echo "  - Conquistas Desbloqueadas"
echo ""
echo "✨ O sistema está pronto para uso!"
echo "   Boa sorte alcançando streaks longas! 🚀"
