#!/bin/bash

# Script para testar o sistema de aprendizado da IA
# Execute isto após iniciar o servidor

echo "=========================================="
echo "🧪 TESTE DO SISTEMA DE APRENDIZADO DA IA"
echo "=========================================="
echo ""
echo "✅ Mudanças implementadas:"
echo "   1. Penalizações muito mais fortes (-25 a -50)"
echo "   2. Bônus muito mais altos (+15 a +25)"
echo "   3. Limite mínimo 58-65% (era 50%)"
echo "   4. Bloqueio automático de padrões ruins"
echo "   5. Aprendizado muito mais rápido"
echo ""
echo "=========================================="
echo ""
echo "📋 PASSOS PARA TESTAR:"
echo ""
echo "1. ABRA O NAVEGADOR"
echo "   → URL: http://localhost:5173"
echo ""
echo "2. ABRA O CONSOLE (F12)"
echo "   → DevTools > Console"
echo ""
echo "3. EXECUTE ESTES COMANDOS PARA VERIFICAR:"
echo ""
echo "   // Ver configuração atual"
echo "   aiLearningSystem.getLearningState()"
echo ""
echo "   // Ver thresholds mínimos"
echo "   aiLearningSystem.getOperationalConfig()"
echo ""
echo "   // Ver histórico completo"
echo "   aiLearningSystem.getHistory()"
echo ""
echo "=========================================="
echo ""
echo "4. TESTE A GERAÇÃO DE SINAIS:"
echo "   ✓ Clique em 'Gerar Sinal' manualmente, OU"
echo "   ✓ Ative 'Auto-Geração' com intervalo 30s"
echo ""
echo "5. OBSERVE NO CONSOLE:"
echo "   ✓ Mensagens de rejeição com motivo"
echo "   ✓ Cálculo de penalizações/bônus"
echo "   ✓ Sinais com 98% aparecem raramente"
echo ""
echo "6. REGISTRE RESULTADOS:"
echo "   ✓ Para cada sinal: WIN ou LOSS"
echo "   ✓ Observe ajustes automáticos"
echo ""
echo "=========================================="
echo ""
echo "🎯 TESTES ESPERADOS:"
echo ""
echo "TESTE 1: Padrão Fraco (< 40% histórico)"
echo "   Ação: Penalização -30 a -45"
echo "   Resultado: Sinal rejeitado"
echo ""
echo "TESTE 2: Padrão Forte (> 70% histórico)"
echo "   Ação: Bônus +20 a +25"
echo "   Resultado: Sinal aceito com alta confiança"
echo ""
echo "TESTE 3: Win Rate Muito Baixo (< 40%)"
echo "   Ação: Min threshold aumenta para 65%"
echo "   Resultado: Menos sinais, mais seletivo"
echo ""
echo "TESTE 4: 5 LOSS consecutivos = Bloqueio"
echo "   Ação: Padrão adicionado a 'disallowedPatterns'"
echo "   Resultado: Nunca mais gera com aquele padrão"
echo ""
echo "=========================================="
echo ""
echo "📊 MONITORAR ESTAS MÉTRICAS:"
echo ""
echo "   aiLearningSystem.getLearningState().winRate"
echo "   aiLearningSystem.getLearningState().bestIndicators"
echo "   aiLearningSystem.getLearningState().evolutionPhase"
echo "   aiLearningSystem.getLearningState().patternSuccessRates"
echo ""
echo "=========================================="
echo ""
echo "✅ Se vir essas mensagens no console, está funcionando:"
echo ""
echo "   🔴 PADRÃO MUITO FRACO DETECTADO"
echo "   📉 PADRÃO PENALIZADO"
echo "   ✅ PADRÃO FORTE DETECTADO"
echo "   📈 PADRÃO REFORÇADO"
echo "   🔥 AJUSTE AGRESSIVO"
echo "   🚨 CRÍTICO: Win Rate EXTREMAMENTE baixo"
echo ""
echo "=========================================="
echo ""
echo "🚀 COMECE O TESTE!"
echo ""
